---
- name: Add Jenkins gpg key and yum repository.
  yum_repository:
    name: jenkins
    description: Jenkins LTS.
    baseurl: https://pkg.jenkins.io/redhat-stable
    gpgkey: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
    gpgcheck: yes
    # update_cache: true

- name: Install JRE
  yum: name=java-11-openjdk-devel state=present


- name: Install Jenkins
  yum: name=jenkins state=present

- name: Configure Jenkins #make jenkins invisible from outside
  lineinfile:
    dest=/etc/default/jenkins
    regexp='^JENKINS_ARGS='
    line='JENKINS_ARGS="--webroot=/var/cache/$NAME/war --httpPort=$HTTP_PORT --httpListenAddress=127.0.0.1"'
  notify:
    - restart jenkins



- name: Enable and start Jenkins
  service: name=jenkins state=started enabled=true


- name: Install nginx
  yum: name=nginx state=present


- name: Configure nginx proxy
  import_tasks: configure_nginx.yml
  notify:
    - restart nginx


- name: Enable and start
  service: name=nginx state=started enabled=true
